name: vpas
github: majkrzak/vpas
author: Piotr Majkrzak

dependencies:
- base
- net-mqtt
- aeson
- bytestring
- unordered-containers
- stm
- req
- vector
- naqsha

ghc-options:
- -dynamic
- -threaded

default-extensions:
- DuplicateRecordFields
- TypeSynonymInstances
- FlexibleInstances
- RecordWildCards
- OverloadedStrings
- LambdaCase

executable:
  main: Main.hs
  source-dirs: src
